[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true
